### PR TITLE
created a directory netcdf-java

### PR DESCRIPTION
**Pull request by JacinthEsther**

### CODE REVIEW

**Review by joshmoore — CHANGES_REQUESTED** [review]
Hi @JacinthEsther, thanks for working on this. It looks like _all_ the files locally were added to your branch. Many of them are generated automatically and so shouldn't be committed into git. The files we need should match those for the jzarr directory:

```
$ git ls-files generate_data/jzarr/
generate_data/jzarr/generate_data.sh
generate_data/jzarr/pom.xml
generate_data/jzarr/src/main/java/zarr_implementations/jzarr/App.java
```

but with "jzarr" replaced with "netcdf". For example:

```
generate_data/netcdf-java/generate_data.sh
generate_data/netcdf-java/pom.xml
generate_data/netcdf-java/src/main/java/zarr_implementations/netcdf_java/App.java
```

**Comment by jakirkham** [comment]
Would it make sense to update `.gitignore` to help filter these out?

**Comment by joshmoore** [comment]
> Would it make sense to update `.gitignore` to help filter these out?

Almost certainly! :+1:

**Comment by JacinthEsther** [comment]
I don't quite understand the response please

**Comment by jakirkham** [comment]
Think Josh is saying to drop [the Maven files]( https://github.com/github/gitignore/blob/e5323759e387ba347a9d50f8b0ddd16502eb71d4/Maven.gitignore ) (though I could be misunderstanding)

**Comment by joshmoore** [comment]
> I don't quite understand the response please

I think there should only be three files in this PR, @JacinthEsther. Currently there are 67 files:

https://github.com/zarr-developers/zarr_implementations/pull/58/files

The files should be named "App.java", "pom.xml", and "generate_data.sh". They should all be in the `netcdf-java` directory.

**Comment by joshmoore** [comment]
Closing in favor of #59

**Pull request closed without merging**
