### PR TITLE
add zarr v3 data generated using zarrita

### PR DESCRIPTION
**Pull request by grlee77**
This PR adds .zr3 data as proposed in #22 

It introduces a new function in ac402df that uses [zarrita](https://github.com/alimanfoo/zarrita) to generate zarr v3 data. The data itself was added in the second commit here.

Currently this script requires the small modifications in alimanfoo/zarrita#36 in order for all of the codecs to work.

A few initial questions:
1. Should this data generation be in a separate `generate_zarrita.py` file rather than adding it to the existing `generate_zarr.py`? It seems @carreau has been implementing the v3 spec in zarr-python as well, so perhaps that is what should go in the existing file instead. Having a separate file would also enable creating a separate entry for the v3 data in the top level `Makefile`.

2. The v3 data is currently organized under a single `data/zarr.zr3` hierarchy where each codec is represented via a separate array within that hierarchy. Is that the organization that was envisioned? It would also be possible to store each codec in its own independent hierarchy.

3. Is the zarrita implementation itself also supposed to be incorporated into this repository or just the data generated by it?

4. The intention would be to also add follow-up PRs with separate .zr3 files for other implementations of the v3 spec? (e.g. zarr-python, zarrita.js and xtensor-zarr)

### CODE REVIEW

**Comment by joshmoore** [comment]
1. I was thinking a separate `generate_zarrita.py` (as well as `generate_zarrV3.py` for the interim)
2. I don't have a strong opinion. @constantinpape? My tendency would be to choose what will make it easier to growth the numer of implementations here.
3. You mean reading the files? If so, yes, it should be reading the v3 data with the next source being `generate_zarrV3.py`.
4. Exactly!

**Comment by constantinpape** [comment]
1. Yes, I would put it in a separate file.
2. Yes, that's exactly how it's envisioned.  It would be better to call the file `zarrita.z3` though, because `zarr.z3` would be what's generated by `zarr-python` (at least following the current logic of the file organisation).
3. I am also not quite sure what by this. The data generation script should go in here (but I see that it's part of the PR already) and then generating the data and running compatibility tests should be included into the CI (although we can't really run compatability yet as this is the first zarr v3 file).
4. Yes, exactly. Then we would update the CI to check that the outputs from the different libraries for the v3 file format are compatible.

**Comment by grlee77** [comment]
Okay, I think things are now named and organized in a more logical manner.

The four new test cases can be run using: `pytest test/ -v -k zarrita` from the source directory (With zarrita branch https://github.com/alimanfoo/zarrita/pull/36 this now pass locally for me)

**Comment by constantinpape** [comment]
Looks good, now we only need to install zarrita in the CI somehow, maybe using pip to install it from github?

**Comment by joshmoore** [comment]
@grlee77: I'd think it's fine to do that install from your branch for the moment.

**Review by joshmoore — APPROVED** [review]
```
test/test_read_all.py::test_correct_read[read js zarr using z5py, blosc] PASSED [  1%]
test/test_read_all.py::test_correct_read[read js zarr using z5py, gzip] PASSED [  3%]
test/test_read_all.py::test_correct_read[read js zarr using z5py, raw] PASSED [  4%]
test/test_read_all.py::test_correct_read[read js zarr using z5py, zlib] PASSED [  6%]
test/test_read_all.py::test_correct_read[read js zarr using zarr, blosc] PASSED [  8%]
test/test_read_all.py::test_correct_read[read js zarr using zarr, gzip] PASSED [  9%]
test/test_read_all.py::test_correct_read[read js zarr using zarr, raw] PASSED [ 11%]
test/test_read_all.py::test_correct_read[read js zarr using zarr, zlib] PASSED [ 12%]
test/test_read_all.py::test_correct_read[read xtensor_zarr zarr using z5py, blosc] PASSED [ 14%]
test/test_read_all.py::test_correct_read[read xtensor_zarr zarr using z5py, gzip] PASSED [ 16%]
test/test_read_all.py::test_correct_read[read xtensor_zarr zarr using z5py, raw] PASSED [ 17%]
test/test_read_all.py::test_correct_read[read xtensor_zarr zarr using z5py, zlib] PASSED [ 19%]
test/test_read_all.py::test_correct_read[read xtensor_zarr zarr using zarr, blosc] PASSED [ 20%]
test/test_read_all.py::test_correct_read[read xtensor_zarr zarr using zarr, gzip] PASSED [ 22%]
test/test_read_all.py::test_correct_read[read xtensor_zarr zarr using zarr, raw] PASSED [ 24%]
test/test_read_all.py::test_correct_read[read xtensor_zarr zarr using zarr, zlib] PASSED [ 25%]
test/test_read_all.py::test_correct_read[read z5py zarr using z5py, blosc] PASSED [ 27%]
test/test_read_all.py::test_correct_read[read z5py zarr using z5py, gzip] PASSED [ 29%]
test/test_read_all.py::test_correct_read[read z5py zarr using z5py, raw] PASSED [ 30%]
test/test_read_all.py::test_correct_read[read z5py zarr using z5py, zlib] PASSED [ 32%]
test/test_read_all.py::test_correct_read[read z5py zarr using zarr, blosc] PASSED [ 33%]
test/test_read_all.py::test_correct_read[read z5py zarr using zarr, gzip] PASSED [ 35%]
test/test_read_all.py::test_correct_read[read z5py zarr using zarr, raw] PASSED [ 37%]
test/test_read_all.py::test_correct_read[read z5py zarr using zarr, zlib] PASSED [ 38%]
test/test_read_all.py::test_correct_read[read zarr zarr using z5py, blosc] PASSED [ 40%]
test/test_read_all.py::test_correct_read[read zarr zarr using z5py, gzip] PASSED [ 41%]
test/test_read_all.py::test_correct_read[read zarr zarr using z5py, raw] PASSED [ 43%]
test/test_read_all.py::test_correct_read[read zarr zarr using z5py, zlib] PASSED [ 45%]
test/test_read_all.py::test_correct_read[read zarr zarr using zarr, blosc] PASSED [ 46%]
test/test_read_all.py::test_correct_read[read zarr zarr using zarr, gzip] PASSED [ 48%]
test/test_read_all.py::test_correct_read[read zarr zarr using zarr, raw] PASSED [ 50%]
test/test_read_all.py::test_correct_read[read zarr zarr using zarr, zlib] PASSED [ 51%]
test/test_read_all.py::test_correct_read[read n5-java N5 using z5py, gzip] PASSED [ 53%]
test/test_read_all.py::test_correct_read[read n5-java N5 using z5py, raw] PASSED [ 54%]
test/test_read_all.py::test_correct_read[read n5-java N5 using pyn5, bzip2] PASSED [ 56%]
test/test_read_all.py::test_correct_read[read n5-java N5 using pyn5, gzip] PASSED [ 58%]
test/test_read_all.py::test_correct_read[read n5-java N5 using pyn5, raw] PASSED [ 59%]
test/test_read_all.py::test_correct_read[read n5-java N5 using zarr, gzip] PASSED [ 61%]
test/test_read_all.py::test_correct_read[read n5-java N5 using zarr, raw] PASSED [ 62%]
test/test_read_all.py::test_correct_read[read pyn5 N5 using z5py, gzip] PASSED [ 64%]
test/test_read_all.py::test_correct_read[read pyn5 N5 using z5py, raw] PASSED [ 66%]
test/test_read_all.py::test_correct_read[read pyn5 N5 using pyn5, bzip2] PASSED [ 67%]
test/test_read_all.py::test_correct_read[read pyn5 N5 using pyn5, gzip] PASSED [ 69%]
test/test_read_all.py::test_correct_read[read pyn5 N5 using pyn5, raw] PASSED [ 70%]
test/test_read_all.py::test_correct_read[read pyn5 N5 using zarr, gzip] PASSED [ 72%]
test/test_read_all.py::test_correct_read[read pyn5 N5 using zarr, raw] PASSED [ 74%]
test/test_read_all.py::test_correct_read[read z5py N5 using z5py, gzip] PASSED [ 75%]
test/test_read_all.py::test_correct_read[read z5py N5 using z5py, raw] PASSED [ 77%]
test/test_read_all.py::test_correct_read[read z5py N5 using pyn5, gzip] PASSED [ 79%]
test/test_read_all.py::test_correct_read[read z5py N5 using pyn5, raw] PASSED [ 80%]
test/test_read_all.py::test_correct_read[read z5py N5 using zarr, gzip] PASSED [ 82%]
test/test_read_all.py::test_correct_read[read z5py N5 using zarr, raw] PASSED [ 83%]
test/test_read_all.py::test_correct_read[read zarr N5 using z5py, gzip] PASSED [ 85%]
test/test_read_all.py::test_correct_read[read zarr N5 using z5py, raw] PASSED [ 87%]
test/test_read_all.py::test_correct_read[read zarr N5 using pyn5, gzip] PASSED [ 88%]
test/test_read_all.py::test_correct_read[read zarr N5 using pyn5, raw] PASSED [ 90%]
test/test_read_all.py::test_correct_read[read zarr N5 using zarr, gzip] PASSED [ 91%]
test/test_read_all.py::test_correct_read[read zarr N5 using zarr, raw] PASSED [ 93%]
test/test_read_all.py::test_correct_read[read zarrita zarr-v3 using zarrita, blosc] PASSED [ 95%]
test/test_read_all.py::test_correct_read[read zarrita zarr-v3 using zarrita, gzip] PASSED [ 96%]
test/test_read_all.py::test_correct_read[read zarrita zarr-v3 using zarrita, raw] PASSED [ 98%]
test/test_read_all.py::test_correct_read[read zarrita zarr-v3 using zarrita, zlib] PASSED [100%]
```

And so it begins! 🎉 

@grlee77 : if you can capture an issue to remind us to come back and replace your branch with @alimanfoo's on merge, then I'd say we consider this done and see how the zarr-python v3 interacts.

**Comment by grlee77** [comment]
I opened #28 to remind us to update `environment.yml` later. I can start looking at zarr-python today. I will try to rebase what is in @carreau's `spec-v3` branch onto current master and see if it works for this case.

**Pull request merged**
