### PR TITLE
Add xtensor-zarr

### PR DESCRIPTION
**Pull request by davidbrochart**

### CODE REVIEW

**Comment by davidbrochart** [comment]
Trigger CI

**Comment by davidbrochart** [comment]
It looks like the failures are due to the grid overhanging the edge of the array space, e.g. chunk `5.5.0` with shape `(100, 100, 1)` has unused data since only the slice `(:12, :12, :1)` is relevant. xtensor-zarr doesn't store the unused data, which looks like a bug.

**Comment by joshmoore** [comment]
One point for `zarr_implementations`! 🎉 Really excited to have xtensor added here, @davidbrochart.

**Comment by davidbrochart** [comment]
Indeed Josh, this exercise was useful! We have a fix coming :smile:

**Review by constantinpape — APPROVED** [review]
Looks good!
Do you want to add anything else, @davidbrochart? Otherwise I am very happy to merge this :).

Also, we should eventually add a test that reads the other zarr data with xtensor-zarr, but this is currently also lacking for the other non-python implementations, see #25.
So from my side it's totally ok to do this later in another PR.

**Comment by davidbrochart** [comment]
Yes, I think we can merge this PR and I'll open another one for reading other zarr data with xtensor-zarr.

**Comment by grlee77** [comment]
I tried extending the data generation program to also generate an `xtensor_zarr.zr3` v3 format file as well, but haven't succeeded yet. I opened an issue regarding it at xtensor-stack/xtensor-zarr#38

**Pull request merged**
