### PR TITLE
add developer guide

### PR DESCRIPTION
**Pull request by grlee77**
I wrote up some documentation on the data generation and testing strategy intended for developers wanting to add a new library to `zarr_implementations`.

Right now this is just in the format of a Markdown file. GitHub will render it for you if you select the "view file" option in the options  when reviewing the newly added `development_overview.md` file.

I was not sure what is the desired documentation approach to take for this repository. I am most familiar with using sphinx for API documentation, but I don't think that is particularly necessary for this project. Maybe GitHub Pages is a simpler option in this case? Even if we don't set up documentation hosting immediately, we can add a link to this Markdown in the top-level README and other devs could see it rendered on GitHub itself. Let me know what you want to try and I can look into it a bit more.

I started looking a little at GitHub pages because I thought that it should be possible to deploy the test summary reports there automatically via a GitHub Action rather than storing them as artifacts that are relatively hard to find and view.

cc @joshmoore

### CODE REVIEW

**Comment by grlee77** [comment]
I mentioned jzarr in the text, but its PR has not been merged yet. If we keep `jzarr` in the text here, I should also add it to the table listing the implementations.

**Comment by grlee77** [comment]
Regarding deployment of reports, if we use GitHub Pages here, the following action seems to work: https://github.com/JamesIves/github-pages-deploy-action. We could have a static site where the reports would be updated on merges to main.

Basically this involves:
1.) enable Pages in the repository settings
2.) creating a gh-pages branch with the static site content (e.g. like the doc in this PR)
3.) add several lines using `github-pages-deploy-action` to `.github/workflows/build.yml`

**Comment by joshmoore** [comment]
> https://github.com/zarr-developers/zarr_implementations/pull/44#issuecomment-832120699 but its PR has not been merged yet

Should be good to go now.

> 1.) enable Pages in the repository settings

Already is: https://zarr-developers.github.io/zarr_implementations/

> 2 & 3)

Can the workflow also do that pushing?

**Comment by joshmoore** [comment]
Ack. Sorry, @grlee77! Shall we try to get get this in?

**Comment by joshmoore** [comment]
Re-opening to trigger action.

**Comment by jakirkham** [comment]
Agree getting this in seems like a good idea. We can always refine things in subsequent PRs :)

**Comment by joshmoore** [comment]
:+1: The checks here are all green. For some reason (change of available actions?) the commit itself hasn't got a check.

**Comment by joshmoore** [comment]
Merging and we can get to / cleanup the jzarr reference and publication down the road.

**Pull request merged**
