### PR TITLE
remove generated data files

### LINKED ISSUE #29: storage of data files in the repository
I wanted to raise a question of whether we should be storing any of the generated binary files in this repository? I did add them in #24 based on prior examples, but I see that the recent xtensor-zarr PR did not.

One annoyance is that if I run `make data` locally it will cause git to consider all of these files to be updated (although we could fix that with `.gitignore`). Another, is that if I run the tests locally using the files stored in the repo (generating only the absent xtensor-zarr data via `make xtensor-zarr`), I see the following failure:

```
FAILED test/test_read_all.py::test_correct_read[read z5py zarr using zarr, gzip] - OSError: Not a gzipped file (b'x^')
```

However, all tests pass if I regenerate the data with `make data` rather than using the ones stored in the repository.

### PR DESCRIPTION
**Pull request by grlee77**
close #29

As discussed in #29, as the number of tested libraries and codecs increases, it does not make sense to continue storing all generated data in the repository.

Three representative datasets (zarr v2, zarr v3 and n5) were moved from the `data` subfolder to a new `example` subfolder as suggested by @constantinpape . The other folders have been removed. 

If desired we can also potentially try to purge the removed folders from the .git history to reduce the repository size (the size when cloning the repository is currently around 8.5 MB). If we really want to minimize the overall size, the example data could also be moved to a separate repo.

The only change aside from the above move/remove operations is an update to `.gitignore`

### CODE REVIEW

**Comment by grlee77** [comment]
There is a segfault during the building of `xtensor-zarr` here that was also seen today in a trivial update to #30, so I don't think it is caused by the changes in this PR. I do not see the issue locally and will have to look into it (perhaps a problem with an update in one of the conda package versions?).

**Comment by grlee77** [comment]
@davidbrochart : I observed a segfault on CI and locally when running the current xtensor zarr data generation script if the conda environment installed (xtensor 0.23.5 / xtensor-io 0.12.5). Everything works okay with the previous (xtensor 0.23.4/xtensor-io 0.12.4). I don't know if the underlying issue is in `xtensor` or `xtensor-io`, so I was unsure where to raise the issue on the xtensor side?

**Comment by davidbrochart** [comment]
Thanks @grlee77, I can reproduce locally. No need to raise an issue, we are in the middle of a release which can have broken xtensor-zarr. Once we're through, I will open a PR for the zarr v3 support and also for reading other zarr stores from xtensor-zarr.

**Comment by grlee77** [comment]
> Once we're through, I will open a PR for the zarr v3 support and also for reading other zarr stores from xtensor-zarr.

Sounds great! Thanks for the quick update. For now I just opened #32 to avoid this specific failing version on CI so we can have working CI for other PRs unrelated to xtensor.

**Comment by constantinpape** [comment]
> If desired we can also potentially try to purge the removed folders from the .git history to reduce the repository size (the size when cloning the repository is currently around 8.5 MB). If we really want to minimize the overall size, the example data could also be moved to a separate repo.

For now, I don't think that's a major concern. If reducing the size becomes critical we can still revisit this.

> The only change aside from the above move/remove operations is an update to `.gitignore`

Looks like this introduced some merge conflicts with #30. I can merge as soon as that's fixed.

**Comment by grlee77** [comment]
It should be good to go now. I fixed the conflict with `.gitignore`.

**Review by constantinpape — APPROVED** [review]
Thanks!

**Pull request merged**
